### ISSUE TITLE
Tracking issue for CI testing

### ISSUE THREAD

**Issue by miraclx** [calimero-network/core#265]
Items (in no particular order):

- [ ] Rust - 3d
	- [x] `cargo test` all crates that have unit tests
	- [x] `cargo fmt` to ensure styling consistency
	- [x] `cargo clippy` to lint
	- ^~~ fundamental pieces (tracked by https://github.com/calimero-network/core/issues/586)
	- [ ] `cargo check` to ensure the `HEAD` builds right
		- [ ] We need to walk the dep tree, creating a dependency graph and build each crate in order of dependence so we can guarantee all crates build independently as well as when linked. (See https://github.com/calimero-network/core/pull/258#discussion_r1593846781)
		- [ ] Don't forget to build examples
	- [ ] `cargo udeps` /& `cargo machete`  to flag unused deps in each crate's manifest
		- [ ] Perhaps even instructing `rustc` to warn on `unused-crate-dependencies`  by default (`.cargo/config.toml`) and denying warnings in CI so they're hard errors.
		- The key concern here will be false positives due to feature flags or any dependencies of codegen.
	- [x] `cargo deny` to govern dependency deduplication & licenses
	- [ ] cleanup all the `cargo deny` deduplication & licenses warnings and issues which make sense
	- [ ] `cargo audit` to flag security vulnerabilities
	- [ ] Eventually, some testing code coverage
- [ ] Research - 1d
	- [ ] Some way of guaranteeing primitives are lightweight 🤷🏽 (estimate is for research only)
	- [ ] Code compliance enforcer with a tool like or comparable to [themis](https://github.com/near/nearcore/blob/9932e95c5c49262189bc4737366ce46bb2b953c8/tools/themis/src/rules.rs) (estimate is for research only)
