### ISSUE TITLE
Pre-Roadmap: Documentation

### ISSUE THREAD

**Issue by xilosada** [calimero-network/core#432]
- [ ] @danwilliams : Runtime (docs + mermaid)
- [ ] @miraclx : Context/Storage (docs + mermaid)
- [ ] @danwilliams : State (docs + mermaid)
- [ ] @petarjuki7 : Network (public docs + comand help)
- [ ] @MatejVukosav : tooling (docs, npx create-calimero-app, mero-dev npm package)
- [ ] @frdomovic : admin + identity (docs + mermaid)
- [ ] @xilosada : Generic Externalities (docs + mermaid)
