### ISSUE TITLE
Context coordinator joining ceremony

### ISSUE THREAD

**Issue by fbozic** [calimero-network/core#537]
At the moment, the user must run `meroctl` context join command against the coordinator node. Implement coordinator joining ceremony for the context. Part of the context creation process should include an automated coordinator joining process. 

Rough idea:
- The context creator should broadcast a request for coordination to a dedicated topic.
- All (interested) coordinators should reply with a coordination offer. 
- A context creator picks the most suitable offer and broadcasts the offer acceptance. 
- The coordinator whose offer is accepted should join the context topic.
- Consider storing the chosen coordinator for context and validating transaction confirmation/rejection.

Subtasks
- [x] https://github.com/calimero-network/core/issues/582
- [x] https://github.com/calimero-network/core/issues/583
- [x] https://github.com/calimero-network/core/issues/584

**Comment by MatejVukosav** [comment]
Deprecating in favour of a new synchronization mechanism using CRDT
