### ISSUE TITLE
Private Context

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#551]
### Overview

Introduce Private Contexts to the Calimero network to allow peers to communicate securely within specific subgroups of peers. This includes implementing mechanisms for discovery, invitation, and encryption of transactions within these private contexts.

### Goals

- Enable the creation and management of Private Contexts.
- Implement secure discovery and invitation mechanisms.
- Ensure all transactions within a Private Context are encrypted.
- One of the key areas to cover is how encryption is managed for new joiners and leavers.

- [ ] https://github.com/calimero-network/core/issues/632
- [ ] https://github.com/calimero-network/core/issues/637
- [ ] https://github.com/calimero-network/core/issues/642
- [ ] https://github.com/calimero-network/core/issues/651

**Comment by MatejVukosav** [comment]
1. Requirement 1 - enable user to create public or private context through UI or CLI
2. Requirement 2 - enable user to invite other peer to his private context through UI or CLI
3. Requirement 3 - enable invited user to see joined context through UI or CLI (after he was invited)
4. Requirement 4 - enable user to invite other peers to his private context through UI or CLI
5. Requirement 5 - enable user to see data inside context that were generated before he joined
6. Requirement 6 - private context data should not be accessible to the nodes that are not members 
7. Requirement 7 - private context members list should not be accessible to the nodes that are not part of private context 
8. Requirement 8 - prevent user from reading data inside private context after he has been removed from the private context
9. Requirement 9 - enable owner to remove member from the private context through UI or CLI
10. Requirement 10 - enable owner to see list of all private context members through UI or CLI

**Comment by miraclx** [comment]
Resolved
