### ISSUE TITLE
Secure Login Flow 

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#569]
### Implementation

- [x] https://github.com/calimero-network/core/issues/570
- [x] https://github.com/calimero-network/core/issues/571
- [x] https://github.com/calimero-network/core/issues/572
- [x] https://github.com/calimero-network/core/issues/573
- [x] https://github.com/calimero-network/core/issues/574
- [x] https://github.com/calimero-network/core/issues/575
- [x] https://github.com/calimero-network/core/issues/576
- [x] https://github.com/calimero-network/core/issues/577

**Comment by MatejVukosav** [comment]
Take inspiration from here https://github.com/calimero-network/core/issues/414
