### ISSUE TITLE
Synchronisation and merging

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#637]
- [x] https://github.com/calimero-network/core/issues/638
- [x] https://github.com/calimero-network/core/issues/639
- [x] https://github.com/calimero-network/core/issues/640
- [x] https://github.com/calimero-network/core/issues/641

**Comment by miraclx** [comment]
Resolved
