### ISSUE TITLE
Developer interfaces

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#642]
- [x] https://github.com/calimero-network/core/issues/643
- [x] https://github.com/calimero-network/core/issues/644
- [x] https://github.com/calimero-network/core/issues/645

**Comment by miraclx** [comment]
Resolved
