### ISSUE TITLE
Blockchain for configuration management

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#646]
- [x] https://github.com/calimero-network/core/issues/647
- [x] https://github.com/calimero-network/core/issues/648
- [ ] https://github.com/calimero-network/core/issues/649
- [x] https://github.com/calimero-network/core/issues/650
