### ISSUE TITLE
Encryption and key management

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#651]
- [x] https://github.com/calimero-network/core/issues/652
- [x] https://github.com/calimero-network/core/issues/653
- [x] https://github.com/calimero-network/core/issues/654
- [x] https://github.com/calimero-network/core/issues/655

**Comment by miraclx** [comment]
Resolved
